/* 
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json.Linq;

namespace Salesforce.MarketingCloud.Model
{
    [DataContract]
    public class TokenRequest
    {
        [DataMember(Name = "client_id")]
        public string ClientId { get; set; }

        [DataMember(Name = "client_secret")]
        public string ClientSecret { get; set; }

        [DataMember(Name = "grant_type")]
        public string GrantType { get; set; }

        [DataMember(Name = "account_id")]
        public string AccountId { get; set; }

        [DefaultValue("")]
        [DataMember(Name = "scope", EmitDefaultValue = false)]
        public string Scope { get; set; }

        public TokenRequest(string clientId, string clientSecret, string accountId, string scope)
        {
            this.ClientId = clientId;
            this.ClientSecret = clientSecret;
            this.GrantType = "client_credentials";
            this.AccountId = accountId;
            this.Scope = scope ?? "";
        }
    }
}
