/* 
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Salesforce.MarketingCloud.Api;
using Salesforce.MarketingCloud.Model;
using Salesforce.MarketingCloud.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Salesforce.MarketingCloud.Test
{
    /// <summary>
    ///  Class for testing EmailDefinitionDescription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmailDefinitionDescriptionTests
    {
        // TODO uncomment below to declare an instance variable for EmailDefinitionDescription
        //private EmailDefinitionDescription instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EmailDefinitionDescription
            //instance = new EmailDefinitionDescription();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmailDefinitionDescription
        /// </summary>
        [Test]
        public void EmailDefinitionDescriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EmailDefinitionDescription
            //Assert.IsInstanceOfType<EmailDefinitionDescription> (instance, "variable 'instance' is a EmailDefinitionDescription");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
