/* 
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Salesforce.MarketingCloud.Api;
using Salesforce.MarketingCloud.Model;
using Salesforce.MarketingCloud.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Salesforce.MarketingCloud.Test
{
    /// <summary>
    ///  Class for testing Options
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptionsTests
    {
        // TODO uncomment below to declare an instance variable for Options
        //private Options instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Options
            //instance = new Options();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Options
        /// </summary>
        [Test]
        public void OptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Options
            //Assert.IsInstanceOfType<Options> (instance, "variable 'instance' is a Options");
        }


        /// <summary>
        /// Test the property 'TrackLinks'
        /// </summary>
        [Test]
        public void TrackLinksTest()
        {
            // TODO unit test for the property 'TrackLinks'
        }

    }

}
