/* 
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Salesforce.MarketingCloud.Api;
using Salesforce.MarketingCloud.Model;
using Salesforce.MarketingCloud.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Salesforce.MarketingCloud.Test
{
    /// <summary>
    ///  Class for testing Subscriptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubscriptionsTests
    {
        // TODO uncomment below to declare an instance variable for Subscriptions
        //private Subscriptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Subscriptions
            //instance = new Subscriptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Subscriptions
        /// </summary>
        [Test]
        public void SubscriptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Subscriptions
            //Assert.IsInstanceOfType<Subscriptions> (instance, "variable 'instance' is a Subscriptions");
        }


        /// <summary>
        /// Test the property 'List'
        /// </summary>
        [Test]
        public void ListTest()
        {
            // TODO unit test for the property 'List'
        }
        /// <summary>
        /// Test the property 'DataExtension'
        /// </summary>
        [Test]
        public void DataExtensionTest()
        {
            // TODO unit test for the property 'DataExtension'
        }
        /// <summary>
        /// Test the property 'AutoAddSubscriber'
        /// </summary>
        [Test]
        public void AutoAddSubscriberTest()
        {
            // TODO unit test for the property 'AutoAddSubscriber'
        }
        /// <summary>
        /// Test the property 'UpdateSubscriber'
        /// </summary>
        [Test]
        public void UpdateSubscriberTest()
        {
            // TODO unit test for the property 'UpdateSubscriber'
        }

    }

}
