/* 
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Salesforce.MarketingCloud.Api;
using Salesforce.MarketingCloud.Model;
using Salesforce.MarketingCloud.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Salesforce.MarketingCloud.Test
{
    /// <summary>
    ///  Class for testing SuccessfulEmailDefinitionDelete
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SuccessfulEmailDefinitionDeleteTests
    {
        // TODO uncomment below to declare an instance variable for SuccessfulEmailDefinitionDelete
        //private SuccessfulEmailDefinitionDelete instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SuccessfulEmailDefinitionDelete
            //instance = new SuccessfulEmailDefinitionDelete();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SuccessfulEmailDefinitionDelete
        /// </summary>
        [Test]
        public void SuccessfulEmailDefinitionDeleteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SuccessfulEmailDefinitionDelete
            //Assert.IsInstanceOfType<SuccessfulEmailDefinitionDelete> (instance, "variable 'instance' is a SuccessfulEmailDefinitionDelete");
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'DeletedDefinitionKey'
        /// </summary>
        [Test]
        public void DeletedDefinitionKeyTest()
        {
            // TODO unit test for the property 'DeletedDefinitionKey'
        }

    }

}
